import random
import sys

import requests
import textwrap
from bs4 import BeautifulSoup

sys.path.insert(0, '..')
import keys


def _get_next_key():

    nxt = keys.PASTEBIN_KEYS.pop(0)
    keys.PASTEBIN_KEYS.append(nxt)

    return nxt


def _wrap_data_with_information(data, paste_url):
    return data + textwrap.dedent(f"""

    This data can also be found in pastebin, at the following URL: {paste_url}""")


def add_paste(new_text):

    new_text = "This dump was automatically generated by 'PopularTorrentBot': https://github.com/tupini07/PopularTorrentBot\n\n" + new_text

    possible = list(
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789")

    random.shuffle(possible)

    paste_name = "".join(possible[:32])

    def try_actual_bin_creation(api_key):

        payload = {
            **api_key,
            "api_option": 'paste',
            "api_paste_code": new_text,
            "api_paste_private": '0',
            "api_paste_name": paste_name,
            "api_paste_expire_date": '6M',
        }

        url = "https://pastebin.com/api/api_post.php"
        response = requests.request("POST", url, data=payload)

        if not response.text.startswith("http"):
            print(response.text)
            return False, "There was some sort of error in pastebin: " + response.text

        else:
            return True, response.text

    succeeded = (False,)
    i = 0
    while not succeeded[0] and i <= len(keys.PASTEBIN_KEYS):
        succeeded = try_actual_bin_creation(_get_next_key())
        i += 1

    if not succeeded[0]:
        raise RuntimeError(succeeded[1])

    else:
        paste_id = succeeded[1].split("/")[-1]
        return "https://pastebin.com/raw/" + paste_id


def get_paste(paste_url, wrap=True):
    paste = requests.request("GET", paste_url).text

    if paste.startswith("<!DOCTYPE HTML>") and "Your paste has triggered our automatic SPAM" not in paste:
        parsed_html = BeautifulSoup(paste, features="html.parser")
        paste = parsed_html.body.find('textarea', attrs={'id': 'paste_code'}).text

    if paste.startswith("This dump was automatically generated"):
        text_to_break = "https://github.com/tupini07/PopularTorrentBot\n\n"
        found_at_index = paste.index(text_to_break)
        paste = paste[found_at_index + len(text_to_break):]

    if wrap:
        return _wrap_data_with_information(paste, paste_url)

    else:
        return paste
